### ISSUE TITLE
Discovery: Upload files

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan2#409]
## User story
As a data publisher, I want to be able to upload files through a user interface, so that I can share my data without having to use a remote file. 

## Details/Tasks
- [x] Determine how to add a file upload widget to the form
- [x] Determine how to deal with validation, whether the file or something else on the form doesn't validate
- [x] Determine how to integrate with standard POD or DCAT distribution schema
- [x] Review existing widgets for a good fit
- [ ] Create visual to confirm the user workflow is reasonably pleasant
- [x] Create implementation ticket

**Comment by dharizza** [comment]
Notes:

- Determine how to add a file upload widget to the form:

Creating custom widget —> [https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/)
This custom widget should have two options: one for adding a URL and other for uploading a file

- Determine how to deal with validation, whether the file or something else on the form doesn't validate

If user chooses url —> we should validate if it is a valid url.
If user chooses a file upload —> we should validate if the resulting uri corresponds to an existing file.

- Determine how to integrate with standard POD or DCAT distribution schema

This would be out of the box, nothing else needs to be done, the widget should return a valid URI and that's what is going to be used.

- Review existing widgets for a good fit

The library react-jsonschema-form provides working widgets:
  - for url —> rjsf with type: string and format uri
  - for file upload —> rjsf with type: string and format: data-url or "ui:widget": "file"

We're thinking about these tickets:

1. Create custom widget that allows users to choose what they want to add (text or file):
  - [ ]  field chooser, two tabs: one for url other for file upload
  - [ ] add validations:
    - If user chooses url —> we should validate if it is a valid url.
    - If user chooses a file upload —> we should validate if the resulting uri corresponds to an existing file.
  - [ ]  both will return an URI, which is what will be saved in the JSON Metadata field
2. Integrate with backend
  - [ ]  check if FileMapper is going to be used and how to integrate it
  - [ ]  how are the files going to be handled? is FileMapper in charge of it? otherwise, check the drupal API, we should probably create something custom, we can check media entity about how to do this

**Comment by dharizza** [comment]
Implementation tickets:
- https://github.com/GetDKAN/dkan/issues/3126
- https://github.com/GetDKAN/dkan/issues/3127

**Comment by drasgardian** [comment]
DKAN1 had three options, so to provide an upgrade path we need some equivalent/mapping for all three.

![Screenshot from 2020-06-12 15-14-12](https://user-images.githubusercontent.com/2704278/84467442-821ea980-acbf-11ea-9083-5bef73eccccc.png)

Feedback from our users was that they found those default labels confusing so we ended up customising the terminology to this:

![Screenshot from 2020-06-12 15-16-56](https://user-images.githubusercontent.com/2704278/84467548-e04b8c80-acbf-11ea-95db-616b307aeb48.png)
